### ISSUE TITLE
node app.js timeout

### ISSUE THREAD

**Issue by shiqikai** [luojinghui/nodejs-ins#1]
执行了 node app.js之后
$ node app.js
{ Error: connect ETIMEDOUT 59.24.3.173:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '59.24.3.173',
  port: 443 }

**Comment by luojinghui** [comment]
@shiqikai
这个需要连着全局vpn，因为访问fb的api

**Comment by shiqikai** [comment]
好的  我再试试。  谢谢!

**Comment by shiqikai** [comment]
先在是报这个错了，  我看文件夹也没有新建。 是不是我环境变量什么的有问题啊。。
$ node app.js
{ Error: getaddrinfo ENOENT api.instagram.com:443
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'api.instagram.com',
  host: 'api.instagram.com',
  port: 443 }

**Comment by luojinghui** [comment]
@shiqikai 非常抱歉，这两天没及时看到消息。请问你使用的是什么平台？win还是mac？对于ins的token，获取的是否成功，你可以在postman上调用相应的api查看接口数据是否返回成功，如果没有，请阅读我[文章](http://luojh.me/2018/01/28/blog2/)查看完成的步骤。

**Comment by shiqikai** [comment]
win和mac都试过啦  接口是get的嘛 放在浏览器posman什么的都能成功，有毒。
大神，能不能你clone项目下来自己试试？
纪念日想给女朋友做个相册功能卡在这了， 不胜感激。

**Comment by luojinghui** [comment]
@shiqikai 如果不介意，你把你的拼好的`baseUrl`通过邮件发给我，我在我这里帮你试一下。我的邮箱：luojinghui424@gmail.com

**Comment by cooguyan** [comment]
已经解决！我也是这个问题。

**Comment by cooguyan** [comment]
## 超时解决办法
在开着vpn的基础上 打开 app.js  
修改为以下代码
//发送请求
``` javascript
request({uri: baseUrl,'proxy':'http://localhost:1080'}, function (error, response, body) {
  if (!error && response.statusCode == 200) {
    let resData = JSON.parse(body).data;
```
以及
```
//下载方法
var download = function (url, dir, filename) {
  request.head(url, function (err, res, body) {
    request({uri: url,'proxy':'http://localhost:1080'}).pipe(fs.createWriteStream(dir + "/" + filename + ".jpg"));
  });
};
```

代码中只有这两个request 操作需要走代理。

其中1080是vpn代理端口号，这个根据你客户端的不同而可能有所不同

**Comment by shiqikai** [comment]
感谢楼上，我先试试

**Comment by cooguyan** [comment]
哇，纪念日还没过么？哈哈，祝好祝好

**Comment by shiqikai** [comment]
哈哈哈  还有几十天     3Q3Q

**Comment by luojinghui** [comment]
@cooguyan @shiqikai 测试了@cooguyan 的关于修正网络延迟的代码，我这边不可以正常抓取数据，网络条件：
![image](https://user-images.githubusercontent.com/12367406/39103461-618709aa-46dd-11e8-8e8c-067983ae253b.png)
可以在postman正常抓取数据，正常访问google，但是执行node app.js会出现题主所出现的超时错误，怀疑是关于网络的原因。

so，更换另一个vpn，
![image](https://user-images.githubusercontent.com/12367406/39103524-cae5a88e-46dd-11e8-963d-3ea38bdd1508.png)

![image](https://user-images.githubusercontent.com/12367406/39103550-055d6ca4-46de-11e8-8133-0afe2f756b4e.png)

执行命令：
```bash
node app.js
```
成功：
![image](https://user-images.githubusercontent.com/12367406/39103589-2f9b8d2a-46de-11e8-9aae-5254f08ba4b2.png)

![image](https://user-images.githubusercontent.com/12367406/39103627-5f9731fa-46de-11e8-9ace-6569ff3642d3.png)

那么，你们也可以按照我的思路尝试使用vpn plus这个软件测试一下。

**Comment by shiqikai** [comment]
@luojinghui 楼主好人~
